# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-PmWiki
version:      0.50
version_from: lib/HTML/WikiConverter/PmWiki.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.5
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
